services:
  api:
    build: ./api
    environment:
      WEB_ORIGIN: ${WEB_ORIGIN:-http://localhost:5173}
      SECRET_KEY: ${SECRET_KEY:-s3cR3t_k3y}
      TOKEN_ISSUER: ${TOKEN_ISSUER:-survey_master}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-surveymasterdb}
    ports:
      - ${FLASK_PORT:-5000}:5000
    volumes:
      - ./api:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-surveymasterdb}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
