name: drs

services:
  api:
    build: ./api
    env_file: ./.env
    environment:
      WEB_ORIGIN: ${WEB_ORIGIN:?error}
      SECRET_KEY: ${SECRET_KEY:?error}
      TOKEN_ISSUER: ${TOKEN_ISSUER:?error}
      FLASK_ENV: ${FLASK_ENV:?error}
      FLASK_DEBUG: ${FLASK_DEBUG:?error}
      POSTGRES_USER: ${POSTGRES_USER:?error}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?error}
      POSTGRES_HOST: ${POSTGRES_HOST:?error}
      POSTGRES_PORT: ${POSTGRES_PORT:?error}
      POSTGRES_DB: ${POSTGRES_DB:?error}
    ports:
      - ${FLASK_PORT:?error}:5000
    volumes:
      - ./api:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    env_file: ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?error}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?error}
      POSTGRES_DB: ${POSTGRES_DB:?error}
    ports:
      - ${POSTGRES_PORT:?error}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
