import os

WEB_ORIGIN = os.getenv("WEB_ORIGIN")
SECRET_KEY = os.getenv("SECRET_KEY")
TOKEN_ISSUER = os.getenv("TOKEN_ISSUER")

POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_HOST = os.getenv("POSTGRES_HOST")
POSTGRES_PORT = os.getenv("POSTGRES_PORT")
POSTGRES_DB = os.getenv("POSTGRES_DB")

SQLALCHEMY_DATABASE_URI = (
    f"postgresql+psycopg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"
)

__all__ = [
    "WEB_ORIGIN",
    "SECRET_KEY",
    "TOKEN_ISSUER",
    "POSTGRES_USER",
    "POSTGRES_PASSWORD",
    "POSTGRES_HOST",
    "POSTGRES_PORT",
    "POSTGRES_DB",
    "SQLALCHEMY_DATABASE_URI",
]
